name: Check Bezrealitky Adverts

on:
  schedule:
    - cron: '*/5 * * * *'   # každých 5 minút
  workflow_dispatch:        # možnosť spustiť manuálne

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run check script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python check_once.py

      - name: Commit seen.json back to repo
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -f seen.json ]; then
            git add seen.json
            git commit -m "Update seen.json from workflow" || echo "No changes to commit"
            git push origin HEAD:${{ github.ref_name }} || echo "Push failed"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
