name: Check Bezrealitky Adverts

on:
  schedule:
    - cron: '*/5 8-21 * * *'   # každých 10 minút od 8:00 do 21:59
  workflow_dispatch:             # možnosť manuálne spustiť

jobs:
  check-adverts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Download seen.json artifact if exists
        uses: actions/download-artifact@v4
        with:
          name: seen
          path: .
        continue-on-error: true   # ak ešte neexistuje, nevadí

      - name: Run check script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python check_once.py

      - name: Upload updated seen.json as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: seen
          path: seen.json

